# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"UnetBlock": "BuildingBlocks.ipynb",
         "UpBlock": "BuildingBlocks.ipynb",
         "Conv2dBlock": "BuildingBlocks.ipynb",
         "LayerNorm": "BuildingBlocks.ipynb",
         "ResBlock": "BuildingBlocks.ipynb",
         "ResBlocks": "BuildingBlocks.ipynb",
         "conv_and_res": "BuildingBlocks.ipynb",
         "DoubleImage": "DataBunch.ipynb",
         "DoubleImageList": "DataBunch.ipynb",
         "MultiUNITDiscriminator": "Discriminator.ipynb",
         "EncoderDecoder": "Encoder&Generator.ipynb",
         "kl_divergence": "Losses.ipynb",
         "disc_loss": "Losses.ipynb",
         "gen_loss": "Losses.ipynb",
         "UNET_UNIT": "TrainLoop.ipynb",
         "GANModule": "TrainLoop.ipynb",
         "GANLoss": "TrainLoop.ipynb",
         "GANTrainer": "TrainLoop.ipynb",
         "FixedGANSwitcher": "TrainLoop.ipynb"}

modules = ["building_blocks.py",
           "data_bunch.py",
           "discriminator.py",
           "encoder_generator.py",
           "losses.py",
           "results.py",
           "train_loop.py",
           "training.py"]

doc_url = "https://BradleyBrown19.github.io/pyfiles/"

git_url = "https://github.com/BradleyBrown19/pyfiles/tree/master/"

def custom_doc_links(name): return None
