# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://BradleyBrown19.github.io/UNET-UNIT/"

git_url = "https://github.com/BradleyBrown19/UNET-UNIT/tree/master/"

def custom_doc_links(name): return None
